name: broadside
channels:
  - conda-forge
dependencies:
  - black
  - dask
  - napari
  - natsort
  - numpy
  - pyinstaller
  - pyqtgraph
  - pyside2
  - pytest
  - python>=3.9
  - scikit-image
  - tifffile
  - tqdm
