name: broadside
channels:
  - conda-forge
  - defaults
dependencies:
  - black>=20.7
  - dask>=2.30
  - napari>=0.4
  - natsort>=7.1
  - numpy>=1.19
  - pyinstaller>=4.0
  - pyqtgraph>=0.11
  - pyside2>=5.13
  - pytest
  - python>=3.8
  - qtpynodeeditor
  - scikit-image
  - shapely
  - tifffile
  - tqdm>=4.53
